name: "Nightly-OSX"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: "Install Electron Packager"
      run: npm install electron-packager -g
    - name: "Install Dependencies"
      run: npm i
    - name: "Install Electron"
      run: npm i electron --save-dev

    - name: "Build macos"
      run: electron-packager . BotCheckNightly-OSX --platform=darwin --arch=x64

    - name: "Upload OSX"
      uses: actions/upload-artifact@v2
      with:
        name: "ScreenRecorderJSNightly OSX-x64"
        path: BotCheckNightly-OSX-darwin-x64
