# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "Nightly"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: "Install Electron Packager"
      run: npm install electron-packager -g
    - name: "Install Dependencies"
      run: npm i
    - name: "Install Electron"
      run: npm i electron --save-dev
    - name: "Build Linux"
      run: electron-packager . BotCheckNightly --platform=linux --arch=x64
    - name: "Build Windows"
      run: electron-packager . BotCheckNightly --platform=win32 --arch=x64
    - name: "Upload Windows"
      uses: actions/upload-artifact@v2
      with:
          name: BotCheck Nightly Windows x64
          path: BotCheck/BotCheckNightly-win32-x64
    - name: "Upload Linux"
      uses: actions/upload-artifact@v2
      with:
        name: BotCheck Nightly Linux x64
        path: BotCheck/BotCheckNightly-linux-x64

